# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       xorg-x11-proto-scrnsaverproto
Summary:    X.Org X11 Protocol scrnsaverproto
Version:    1.2.1
Release:    0
Group:      Development/System
License:    MIT
URL:        http://www.x.org
Source0:    http://xorg.freedesktop.org/releases/individual/proto/scrnsaverproto-%{version}.tar.bz2
Source100:  xorg-x11-proto-scrnsaverproto.yaml
Provides:   scrnsaverproto


%description
This extension defines a protocol to control screensaver features
and also to query screensaver info on specific windows.




%prep
%setup -q -n scrnsaverproto-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --libdir=%{_datadir}

make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post






%files
%defattr(-,root,root,-)
# >> files
%{_datadir}/pkgconfig/scrnsaverproto.pc
%{_includedir}/X11/extensions/saver.h
%{_includedir}/X11/extensions/saverproto.h
%doc %{_docdir}/scrnsaverproto/saver.xml
# << files


